Make Common version requirement less strict
mapbox/mapbox-navigation-native-ios pull request #6
Opened 2021-04-22 13:46 UTC by SiarheiFedartsou

2021-04-22 13:47 UTC, SiarheiFedartsou commented on Package.swift
> +        .package(url: "https://github.com/mapbox/mapbox-common-ios.git", from: mapboxCommonVersion),
According to SPM docs:
```
/// The following example allows the Swift Package Manager to select a version
/// like a  `1.2.3`, `1.2.4`, or `1.3.0`, but not `2.0.0`.
///
///    .package(url: "https://example.com/example-package.git", from: "1.2.3"),
```

Is it okay to allow minor versions in our cases(11.1.0 in this particular case can be installed)?

2021-04-22 18:31 UTC, dersim-davaod requested changes

2021-04-22 18:31 UTC, dersim-davaod commented on Package.swift
> +}
Can we have more generic function? something similar to:

```suggestion
func versionRangeThatAllowsOnlyPatches(for version: Version) -> Range<Version> {
    version..<Version("\(version.major).\(version.minor + 1).0")
}
```
 
Then we can get rid of comment below and use it as:
 ```swift
 .package(url: "https://github.com/mapbox/mapbox-common-ios.git", versionRangeThatAllowsOnlyPatches(for: mapboxCommonVersion)),
```

2021-04-23 13:59 UTC, dersim-davaod commented
Additional comment regarding to the base branch. Currently it is set to `main`, but seems the changes should be landed into the `release-v2.0`. @1ec5 please correct me if I'm wrong.

2021-04-28 22:03 UTC, 1ec5 commented on Package.swift
> +        .package(url: "https://github.com/mapbox/mapbox-common-ios.git", versionRangeThatAllowsOnlyPatches(for: mapboxCommonVersion)),
This is equivalent to `Package.Dependency.Requirement.upToNextMinor(from:)`, which would be clearer than the custom function used here. However, CocoaPods and Carthage don’t quite support the same semantics, at least not for post-v1.0 packages. The only common denominator that works regardless of package manager is `.upToNextMajor(from:)`, which is incidentally the [officially recommended](https://developer.apple.com/documentation/swift_packages/package/dependency/3582850-package#discussion) practice on iOS.

2021-04-28 22:05 UTC, 1ec5 commented
> Additional comment regarding to the base branch. Currently it is set to `main`, but seems the changes should be landed into the `release-v2.0`.

This repository has no release-v2.0 branch because every new release updates main. This does lead to some back-and-forth as v3_x_._y_ releases continue to be published, but it isn‘t a huge deal because the only thing SPM cares about is Package.swift’s current contents as of a particular tag.

2021-05-18 09:41 UTC, dersim-davaod approved these changes
LGTM

2021-05-18 09:53 UTC, merged